export const selectedFood = 0;
export const dishes = [
	{
		id: 0,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/sashimi-salad.jpg",
		name: "Sashimi salad",
		description: "Organic greens topped with fresh sashimi, wasabi soy vinaigrette.",
		price: 12.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 2.9156", "Fat (total): 2.4396", "Carbohydrate: 2.4396", "Energy: (kJ)17.5775", "Energy (kcal): 4.2011", "Sugar: 0.3738"],
	},
	{
		id: 1,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/chirashi-sushi.jpg",
		name: "Chirashi sushi",
		description: "Sushi bar variety with sushi rice.",
		price: 21.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 2.3138", "Fat (total): 0.6041", "Carbohydrate: 0.6041", "Energy (kJ): 7.5314", "Energy (kcal): 1.8000", "Sugar: 0.3114"],
	},
	{
		id: 2,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/seaweed-salad.jpg",
		name: "Seaweed salad",
		description: "A nice seaweed salad.",
		price: 17.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein. 0.229", "Fat (total): 2.2852", "Carbohydrate: 2.2852", "Energy (kJ): 5.1003", "Energy (kcal): 1.2190", "Sugar: 0.0037"],
	},
	{
		id: 3,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/edamame.jpg",
		name: "Edamame",
		description: "Boiled soy beans with salt",
		price: 4.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 0.7436", "Fat (total): 1.9771", "Carbohydrate: 1.9771", "Energy (kJ): 17.294", "Energy (kcal): 4.1334", "Sugar: 0.1028"],
	},
	{
		id: 4,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/miso-soup.jpg",
		name: "Miso soup",
		description: "Soy bean soup with Wacame seaweed, tofu and spring onion.",
		price: 4.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 2.7642", "Fat (total): 2.1552", "Carbohydrate: 2.1552", "Energy (kJ): 9.393", "Energy (kcal): 2.2450", "Sugar: 0.1399"],
	},
	{
		id: 5,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/maguro.jpg",
		name: "Maguro",
		description: "Tuna pieces",
		price: 12.50,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 2.2293", "Fat (total): 0.7329", "Carbohydrate: 0.7329", "Energy (kJ): 28.2176", "Energy (kcal): 6.7442", "Sugar: 0.4018"],
	},
	{
		id: 6,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/shake.jpg",
		name: "Shake",
		description: "",
		price: 10.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 1.4804", "Fat (total): 1.4739", "Carbohydrate: 1.4739", "Energy (kJ): 16.9406", "Energy (kcal): 4.0489", "Sugar0.245"],
	},
	{
		id: 7,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/shiromi.jpg",
		name: "Shiromi",
		description: "White fish pieces.",
		price: 9.50,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 0.2814", "Fat (total): 1.3963", "Carbohydrate: 1.3963", "Energy (kJ): 16.4487", "Energy (kcal): 3.9313", "Sugar: 0.0509"],
	},
	{
		id: 8,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/tekka-maki.jpg",
		name: "Tekka maki",
		description: "Tuna roll with wasabi. - 6 pieces",
		price: 6.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 0.9559", "Fat (total): 1.6395", "Carbohydrate: 1.6395", "Energy (kJ): 9.7847", "Energy (kcal): 2.3386", "Sugar: 0.4771"],
	},
	{
		id: 9,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/hosomaki-mix.jpg",
		name: "Hosomaki Mix",
		description: "18 pieces.",
		price: 17.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 2.683", "Fat (total): 2.858", "Carbohydrate: 2.858", "Energy (kJ): 23.8901", "Energy (kcal): 5.7099", "Sugar: 0.4839"],
	},
	{
		id: 10,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/california-rolls.jpg",
		name: "California rolls",
		description: "Crab sticks, avocado and cucumber. - 8 pieces",
		price: 7.75,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 0.848", "Fat (total): 0.1205", "Carbohydrate: 0.1205", "Energy (kJ): 18.6541", "Energy (kcal): 4.4584", "Sugar: 0.0174"],
	},
	{
		id: 11,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/seattle-rolls.jpg",
		name: "Seattle rolls",
		description: "Smoked salmon. Cucumber. Cream cheese.",
		price: 8.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 2.2802", "Fat (total): 2.309", "Carbohydrate: 2.309", "Energy (kJ): 18.6961", "Energy (kcal): 4.4685", "Sugar: 0.2533"],
	},
	{
		id: 12,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/spicytuna-rolls.jpg",
		name: "Spicy Tuna rolls",
		description: "Spicy tuna, spring onion and avocado. - 6 pieces",
		price: 6.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 1.0003", "Fat (total): 1.5621", "Carbohydrate: 1.5621", "Energy (kJ): 25.0911", "Energy (kcal): 5.9969", "Sugar: 0.0474"],
	},
	{
		id: 13,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/ebi-rolls.jpg",
		name: "Ebi rolls",
		description: "King prawns, avocado and asparagus. - 8 pieces",
		price: 8.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 2.826", "Fat (total): 2.854", "Carbohydrate: 2.854", "Energy (kJ): 19.2756", "Energy (kcal): 4.6070", "Sugar: 0.439"],
	},
	{
		id: 14,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/chicken-teriyaki.jpg",
		name: "Chicken Teriyaki",
		description: "Sauted chicken with teiyaki sauce.",
		price: 12.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 2.2375", "Fat (total): 2.6376", "Carbohydrate: 2.6376", "Energy (kJ): 18.7052", "Energy (kcal): 4.4707", "Sugar: 0.4271"],
	},
	{
		id: 15,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/salmon-teriyaki.jpg",
		name: "Salmon Teriyaki",
		description: "Sauted salmon with teriyaki sauce.",
		price: 13.50,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 2.5748", "Fat (total): 0.0234", "Carbohydrate: 0.0234", "Energy (kJ): 22.7136", "Energy (kcal): 5.4287", "Sugar: 0.1158"],
	},
	{
		id: 16,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/gohan.jpg",
		name: "Gohan",
		description: "Steamed rice.",
		price: 3.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 2.4622", "Fat (total): 2.672", "Carbohydrate: 2.672", "Energy (kJ): 25.1129", "Energy (kcal): 6.0021", "Sugar: 0.3426"],
	},
	{
		id: 17,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/tori-katsu.jpg",
		name: "Tori Katsu",
		description: "Pan-fried chicken breast with yasai salad.",
		price: 11.00,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 1.0267", "Fat (total): 2.2143", "Carbohydrate: 2.2143", "Energy (kJ): 17.8688", "Energy (kcal): 4.2707", "Sugar: 0.0161"],
	},
	{
		id: 18,
		image: "http://demos.telerik.com/kendo-ui/content/spa/websushi/images/200/yaki-udon.jpg",
		name: "Yaki Udon",
		description: "Udon noddles with chicken, king prawns and vegetables.",
		price: 11.50,
		count:1,
		nutritional: "Nutritional Information",
		nutritionalInfo: ["Protein: 1.7697", "Fat (total): 0.2534", "Carbohydrate: 0.2534", "Energy (kJ): 7.508", "Energy (kcal): 1.7945", "Sugar: 0.1798"],
	}
];

export const shopDishes = [];
